language: android
env:
  - TEST_SUITE=units
android:
  components:
    - tools
    - platform-tools
    - build-tools-28-rc1
    - android-27
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
jdk:
    - oraclejdk8
script:
    - ./gradlew clean test -x :app:lint -x :library:lint
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
      - chmod +x ./gradlew
      - yes | sdkmanager "platforms;android-27"
      - yes | sdkmanager "build-tools;28.0.0-rc1"
